### ISSUE TITLE
Typerorr: cannot read property kind of undefined Angular 7

### ISSUE THREAD

**Issue by dionaditya** [ericferreira1992/ag-virtual-scroll#4]
```
ERROR in ./node_modules/ag-virtual-scroll/fesm5/ag-virtual-scroll.js
Module build failed (from ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js):
TypeError: Cannot read property 'kind' of undefined
    at isAngularDecoratorMetadataExpression (/home/dion/website/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:265:35)
    at checkNodeForDecorators (/home/dion/website/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:77:21)
    at visitNodes (/home/dion/website/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16144:30)
    at Object.forEachChild (/home/dion/website/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16370:24)
    at checkNodeForDecorators (/home/dion/website/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
    at visitNode (/home/dion/website/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16135:24)
    at Object.forEachChild (/home/dion/website/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16265:21)
    at checkNodeForDecorators (/home/dion/website/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
    at visitNode (/home/dion/website/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16135:24)
    at Object.forEachChild (/home/dion/website/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16322:24)
    at checkNodeForDecorators (/home/dion/website/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
    at visitNode (/home/dion/website/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16135:24)
    at Object.forEachChild (/home/dion/website/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16333:24)
    at checkNodeForDecorators (/home/dion/website/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
    at visitNode (/home/dion/website/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16135:24)
    at Object.forEachChild (/home/dion/website/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16229:21)
    at checkNodeForDecorators (/home/dion/website/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
    at visitNodes (/home/dion/website/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16144:30)
    at Object.forEachChild (/home/dion/website/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16379:24)
    at checkNodeForDecorators (/home/dion/website/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
    at visitNode (/home/dion/website/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16135:24)
    at Object.forEachChild (/home/dion/website/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16377:21)
```

My Angular Package:
```
@angular-devkit/architect          0.13.10
@angular-devkit/build-angular      0.13.10
@angular-devkit/build-ng-packagr   0.13.10
@angular-devkit/build-optimizer    0.13.10
@angular-devkit/build-webpack      0.13.10
@angular-devkit/core               7.3.10
@angular-devkit/schematics         7.3.10
@angular/cdk                       7.3.7
@angular/cli                       7.3.10
@angular/fire                      5.4.2
@angular/flex-layout               7.0.0-beta.24
@angular/material                  7.3.7
@angular/material-moment-adapter   7.3.7
@ngtools/json-schema               1.1.0
@ngtools/webpack                   7.3.10
@schematics/angular                7.3.10
@schematics/update                 0.13.10
ng-packagr                         4.7.1
rxjs                               6.6.2
typescript                         3.1.6
webpack                            4.29.0
```

Step to reproduce: 
ng build --prod

**Comment by ericferreira1992** [comment]
@dionaditya
The latest version of [ag-virtual-scroll](https://www.npmjs.com/package/ag-virtual-scroll) (1.2.0) only be used with Angular v9 or later. Your project is using Angular v7, so install ag-virtual-scroll version 1.1.0 to work properly, or upgrade your project to Angular v9 or v10 (which would be more recommended)

**Comment by dionaditya** [comment]
@ericferreira1992 It works. Thanks for your quick response. But, I have other problems with this library. My data source was injected from remote server. If I use this library for virtual scroll. I should update height class .content-items manually and do some scroll behaviour to show updated data. My existing approach I do manualy update height class .content-items manually and do some scroll behaviour to show updated data. But, I have weird user experience if user insert new data because scroll bar should move up and go to bottom for showing the updated data. Is it possible to handle data source from remote server?

**Comment by ericferreira1992** [comment]
@dionaditya 
I think I understand the problem. There really is a problem with this and I'll fix it, but for now set a css `height: auto!` Important;` so that you don't have problems with the height of the elements.

**Comment by dionaditya** [comment]
```css height: auto !important;```

whats the element ? Is .content-items?

**Comment by ericferreira1992** [comment]
@dionaditya 
Look example below. The div element with class `.demo-item` is the repeat structured, this is where you must define the `height: auto !important;` (workaround hahaha). Soon I will make the fix and release a new version (but v9 of Angular).

```html
<ag-virtual-scroll #vs [items]="items" height="350px" min-row-height="69" class="box-border">
    <div *ngFor="let item of vs.items" class="demo-item" style="height: auto">
        <div class="demo-item-left">
            <img [src]="item.avatar"/>
        </div>
        <div class="demo-item-right">
            <strong>{{item.name}}</strong>
            <p>Phone: {{item.phone}}</p>
            <p>E-mail: {{item.email}}</p>
        </div>
    </div>
</ag-virtual-scroll>
```
